const STORAGE_KEY = "lowerBackExerciseLog.v1";
const AUTO_BACKUP_KEY = "lowerBackExerciseLog.autoBackup.v1";

const exercises = [
  ["hyperextension", "Гиперэкстензия без отрыва ног", "15-20 повторений", "2020/08/Podem_koprusa_ruki_za_golovoj.gif", "Ляг на живот, ноги вместе, руки у затылка. Поднимай грудь и плечи без рывка, таз и ноги оставляй на полу.", "Укрепляет разгибатели спины, ягодицы и заднюю поверхность бедра.", "Делай меньшую амплитуду или зафиксируй стопы под устойчивой опорой."],
  ["down-up-dog", "Собака вниз в собаку вверх", "10-15 повторений", "2020/08/Iz_sobaki_mordoj_vniz_vverh.gif", "Из положения на руках уведи таз вверх, затем плавно опусти корпус и раскрой грудь в прогибе.", "Мягко вытягивает позвоночник, раскрывает грудной отдел и плечи.", "Слегка согни колени или не уходи глубоко в прогиб."],
  ["bird-dog", "Вытягивание рук и ног", "10-15 на каждую сторону", "2020/10/Ohotnichya_sobaka_new.gif", "На четвереньках вытягивай противоположные руку и ногу в одну линию, затем спокойно меняй сторону.", "Развивает стабильность корпуса, координацию и мышцы поясницы.", "Сначала вытягивай только ногу или только руку."],
  ["glute-bridge", "Мостик, подъем таза лежа", "15-20 повторений", "2020/08/Mostik.gif", "Ляг на спину, стопы ближе к тазу. Поднимай таз до прямой линии от плеч до коленей и опускайся плавно.", "Укрепляет ягодицы и нижнюю часть спины, помогает стабилизировать таз.", "Поднимай таз ниже и держи движение медленным."],
  ["boat", "Лодочка с руками вдоль тела", "10-15 повторений", "2020/08/Superman_ruki_nazad.gif", "Ляг на живот, руки вдоль корпуса. Одновременно чуть поднимай грудь и ноги, не запрокидывая голову.", "Включает мышцы спины, ягодицы и улучшает контроль корпуса.", "Оставь ноги на полу и поднимай только верх корпуса."],
  ["plank-touch", "Касание рукой ноги из планки", "10-15 на каждую сторону", "2020/12/Planka_s_kasaniem_stop.gif", "Из планки на прямых руках уведи таз назад-вверх и тянись рукой к противоположной стопе.", "Нагружает кор, плечи, спину и заднюю поверхность ног.", "Согни колени или касайся голени, если до стопы тянуться сложно."],
  ["cobra", "Низкая кобра в высокую", "10-15 повторений", "2020/08/Kobra_vverh_vniz-1.gif", "Лежа на животе, поставь ладони рядом с грудью и плавно поднимай корпус, сохраняя мягкий прогиб.", "Раскрывает грудную клетку, улучшает подвижность спины.", "Не выпрямляй руки полностью и делай небольшую амплитуду."],
  ["wipers", "Дворники с согнутыми ногами", "10-15 на каждую сторону", "2020/06/Dvornik_sognutie_koleni.gif", "Ляг на спину, руки в стороны, колени согнуты. Переводи ноги вправо и влево, контролируя поясницу.", "Мягко включает косые мышцы живота и снимает напряжение со спины.", "Не опускай колени до пола и уменьши диапазон движения."],
  ["reverse-plank", "Подъем таза из обратной планки", "10-15 повторений", "2020/07/Obratnaya_planka_podem_taza.gif", "Сядь, поставь руки позади таза, ноги вперед. Поднимай таз до прямой линии корпуса и опускай обратно.", "Укрепляет заднюю цепь, ягодицы, кор и поясничный отдел.", "Согни колени или делай движение с меньшей амплитудой."],
  ["leg-raise", "Подъем ног лежа на животе", "10-15 на каждую сторону", "2020/07/Otvedenie_pryamoj_nogi.gif", "Ляг на живот, голову положи на предплечья. Поочередно поднимай прямые ноги без резкого маха.", "Укрепляет ягодицы, заднюю поверхность бедра и мышцы поясницы.", "Поднимай ногу ниже и держись руками за устойчивую опору."],
].map(([id, name, target, image, technique, benefit, easier]) => ({ id, name, target, defaultReps: 0, image: `https://goodlooker.ru/wp-content/uploads/${image}`, technique, benefit, easier }));

const moodLabels = { 5: "Отлично", 4: "Хорошо", 3: "Нормально", 2: "Тяжело", 1: "Плохо" };
let activeDateKey = localDateKey();
let sessionDateWasEdited = false;
const state = { sessions: readSessions(), calendarMonth: new Date(), selectedDate: activeDateKey };
const $ = (selector) => document.querySelector(selector);
const els = {
  tabs: document.querySelectorAll(".tab"), views: document.querySelectorAll(".view"), exerciseList: $("#exerciseList"), exerciseTemplate: $("#exerciseTemplate"), sessionDate: $("#sessionDate"), moodSelect: $("#moodSelect"), painRange: $("#painRange"), painValue: $("#painValue"), sessionNote: $("#sessionNote"), saveSessionButton: $("#saveSessionButton"), exportButton: $("#exportButton"), backupButton: $("#backupButton"), restoreButton: $("#restoreButton"), restoreInput: $("#restoreInput"), autoBackupToggle: $("#autoBackupToggle"), backupStatus: $("#backupStatus"), clearDataButton: $("#clearDataButton"), statSessions: $("#statSessions"), statReps: $("#statReps"), statStreak: $("#statStreak"), statPain: $("#statPain"), weeklyChart: $("#weeklyChart"), chartHint: $("#chartHint"), calendarTitle: $("#calendarTitle"), calendarGrid: $("#calendarGrid"), dayDetail: $("#dayDetail"), prevMonthButton: $("#prevMonthButton"), nextMonthButton: $("#nextMonthButton"), exerciseStats: $("#exerciseStats"), historyList: $("#historyList")
};

init();
function init() { els.sessionDate.value = activeDateKey; els.autoBackupToggle.checked = localStorage.getItem(AUTO_BACKUP_KEY) === "true"; renderExerciseInputs(); bindEvents(); renderAll(); }
function bindEvents() {
  els.tabs.forEach((tab) => tab.addEventListener("click", () => switchView(tab.dataset.view)));
  els.sessionDate.addEventListener("change", () => { sessionDateWasEdited = true; });
  els.painRange.addEventListener("input", () => els.painValue.textContent = `${els.painRange.value}/10`);
  els.saveSessionButton.addEventListener("click", saveSession); els.exportButton.addEventListener("click", shareBackup); els.backupButton.addEventListener("click", shareBackup); els.restoreButton.addEventListener("click", () => els.restoreInput.click()); els.restoreInput.addEventListener("change", restoreBackup);
  els.autoBackupToggle.addEventListener("change", () => { localStorage.setItem(AUTO_BACKUP_KEY, String(els.autoBackupToggle.checked)); setBackupStatus(els.autoBackupToggle.checked ? "Автокопия включена" : "Автокопия выключена"); });
  els.clearDataButton.addEventListener("click", clearData); els.prevMonthButton.addEventListener("click", () => shiftCalendarMonth(-1)); els.nextMonthButton.addEventListener("click", () => shiftCalendarMonth(1));
  window.addEventListener("pageshow", refreshSessionDate);
  window.addEventListener("focus", refreshSessionDate);
  document.addEventListener("visibilitychange", () => { if (!document.hidden) refreshSessionDate(); });
}
function renderExerciseInputs() {
  els.exerciseList.innerHTML = "";
  exercises.forEach((exercise, index) => {
    const node = els.exerciseTemplate.content.firstElementChild.cloneNode(true); node.dataset.exerciseId = exercise.id; node.querySelector(".exercise-number").textContent = index + 1; node.querySelector("h2").textContent = exercise.name; node.querySelector("p").textContent = exercise.target;
    const image = node.querySelector(".exercise-media"); image.src = exercise.image; image.alt = exercise.name; node.querySelector(".technique").textContent = exercise.technique; node.querySelector(".benefit").textContent = exercise.benefit; node.querySelector(".easier").textContent = exercise.easier;
    const input = node.querySelector("input"); input.value = 0; input.dataset.exerciseId = exercise.id; input.setAttribute("aria-label", `${exercise.name}, повторы`);
    node.querySelector(".minus").addEventListener("click", () => input.value = Math.max(0, Number(input.value || 0) - 1)); node.querySelector(".plus").addEventListener("click", () => input.value = Math.min(200, Number(input.value || 0) + 1));
    node.querySelector(".details-toggle").addEventListener("click", (event) => { node.classList.toggle("open"); event.currentTarget.textContent = node.classList.contains("open") ? "Скрыть" : "Техника"; }); els.exerciseList.append(node);
  });
}
function saveSession() {
  refreshSessionDate();
  const entries = exercises.map((exercise) => ({ id: exercise.id, name: exercise.name, reps: clampReps($(`input[data-exercise-id="${exercise.id}"]`).value) })); const totalReps = entries.reduce((sum, item) => sum + item.reps, 0);
  const session = { id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()), date: els.sessionDate.value || localDateKey(), mood: Number(els.moodSelect.value), pain: Number(els.painRange.value), note: els.sessionNote.value.trim(), entries, totalReps, savedAt: new Date().toISOString() };
  const existingIndex = state.sessions.findIndex((item) => item.date === session.date);
  if (existingIndex >= 0 && !confirm(`Тренировка за ${formatDate(session.date)} уже сохранена. Заменить её?`)) return;
  if (existingIndex >= 0) state.sessions[existingIndex] = session; else state.sessions.push(session);
  state.sessions.sort((a, b) => a.date.localeCompare(b.date)); state.selectedDate = session.date; state.calendarMonth = parseLocalDate(session.date); writeSessions(); sessionDateWasEdited = false; els.sessionNote.value = ""; renderAll(); flashSaveButton(); if (els.autoBackupToggle.checked) shareBackup();
}
function refreshSessionDate() {
  const today = localDateKey();
  if (today === activeDateKey) return;
  activeDateKey = today;
  if (!sessionDateWasEdited) els.sessionDate.value = today;
}
function switchView(viewName) { els.tabs.forEach((tab) => tab.classList.toggle("active", tab.dataset.view === viewName)); els.views.forEach((view) => view.classList.toggle("active", view.id === `${viewName}View`)); if (viewName === "stats") drawChart(); }
function renderAll() { renderStats(); drawChart(); renderCalendar(); renderSelectedDay(); renderExerciseStats(); renderHistory(); }
function renderStats() { const totalReps = state.sessions.reduce((sum, s) => sum + s.totalReps, 0); const avgPain = state.sessions.length ? state.sessions.reduce((sum, s) => sum + s.pain, 0) / state.sessions.length : 0; els.statSessions.textContent = state.sessions.length; els.statReps.textContent = totalReps; els.statStreak.textContent = `${calculateStreak()} дн.`; els.statPain.textContent = avgPain.toFixed(1); }
function renderExerciseStats() {
  els.exerciseStats.innerHTML = ""; const totals = exercises.map((exercise) => ({ ...exercise, total: state.sessions.reduce((sum, session) => sum + (session.entries.find((item) => item.id === exercise.id)?.reps || 0), 0) })); const max = Math.max(1, ...totals.map((item) => item.total));
  if (!state.sessions.length) { els.exerciseStats.innerHTML = `<div class="empty-state">После первой тренировки здесь появится разбивка по упражнениям.</div>`; return; }
  totals.forEach((item) => { const line = document.createElement("div"); line.className = "stat-line"; line.innerHTML = `<strong>${item.name}</strong><span>${item.total}</span><progress value="${item.total}" max="${max}"></progress>`; els.exerciseStats.append(line); });
}
function shiftCalendarMonth(direction) { state.calendarMonth = new Date(state.calendarMonth.getFullYear(), state.calendarMonth.getMonth() + direction, 1); renderCalendar(); }
function renderCalendar() {
  els.calendarGrid.innerHTML = ""; const year = state.calendarMonth.getFullYear(); const month = state.calendarMonth.getMonth(); const monthSessions = state.sessions.filter((session) => { const date = parseLocalDate(session.date); return date.getFullYear() === year && date.getMonth() === month; }); const maxReps = Math.max(1, ...monthSessions.map((s) => s.totalReps));
  els.calendarTitle.textContent = new Intl.DateTimeFormat("ru-RU", { month: "long", year: "numeric" }).format(state.calendarMonth); const firstDay = new Date(year, month, 1); const daysInMonth = new Date(year, month + 1, 0).getDate(); const leadingBlanks = (firstDay.getDay() + 6) % 7;
  for (let i = 0; i < leadingBlanks; i++) { const blank = document.createElement("span"); blank.className = "calendar-day blank"; els.calendarGrid.append(blank); }
  for (let day = 1; day <= daysInMonth; day++) { const date = toDateKey(new Date(year, month, day)); const session = state.sessions.find((item) => item.date === date); const button = document.createElement("button"); button.type = "button"; button.className = "calendar-day"; button.dataset.date = date; button.textContent = day; if (session) { button.classList.add("has-session"); button.style.setProperty("--load", Math.max(0.3, session.totalReps / maxReps).toFixed(2)); } if (date === state.selectedDate) button.classList.add("selected"); button.addEventListener("click", () => { state.selectedDate = date; renderCalendar(); renderSelectedDay(); }); els.calendarGrid.append(button); }
}
function renderSelectedDay() {
  const session = state.sessions.find((item) => item.date === state.selectedDate); if (!session) { els.dayDetail.innerHTML = `<div class="empty-state">${formatDate(state.selectedDate)}: тренировки нет. Выбери день с отметкой или сохрани новую тренировку.</div>`; return; }
  const completed = session.entries.filter((e) => e.reps > 0).length; const topEntry = [...session.entries].sort((a, b) => b.reps - a.reps)[0]; const maxReps = Math.max(1, ...session.entries.map((e) => e.reps)); const zeroCount = session.entries.filter((e) => e.reps === 0).length;
  els.dayDetail.innerHTML = `<article class="day-card"><header><div><span>День</span><strong>${formatDate(session.date)}</strong></div><div><span>Итог</span><strong>${session.totalReps}</strong></div></header><div class="day-metrics"><span>${completed}/10 упражнений</span><span>${moodLabels[session.mood]}</span><span>Боль ${session.pain}/10</span><span>${zeroCount ? `Пропущено ${zeroCount}` : "Без пропусков"}</span></div><p class="day-insight">Больше всего: ${topEntry ? `${topEntry.name}, ${topEntry.reps}` : "нет данных"}.</p>${session.note ? `<p class="day-note">${escapeHtml(session.note)}</p>` : ""}<div class="day-exercises">${session.entries.map((entry) => `<div class="day-exercise ${entry.reps ? "" : "empty"}"><span>${entry.name}</span><strong>${entry.reps}</strong><progress value="${entry.reps}" max="${maxReps}"></progress></div>`).join("")}</div></article>`;
}
function renderHistory() { els.historyList.innerHTML = ""; const sessions = [...state.sessions].sort((a, b) => b.date.localeCompare(a.date)); if (!sessions.length) { els.historyList.innerHTML = `<div class="empty-state">Записей пока нет. Сохрани первую тренировку на вкладке “Сегодня”.</div>`; return; } sessions.forEach((session) => { const completed = session.entries.filter((e) => e.reps > 0).length; const entry = document.createElement("article"); entry.className = "history-entry"; entry.innerHTML = `<header><span>${formatDate(session.date)}</span><span>${session.totalReps} повторений</span></header><p>${completed}/10 упражнений, самочувствие: ${moodLabels[session.mood]}, боль: ${session.pain}/10</p>${session.note ? `<p>${escapeHtml(session.note)}</p>` : ""}`; els.historyList.append(entry); }); }
function drawChart() { const ctx = els.weeklyChart.getContext("2d"); const days = lastDays(14); const values = days.map((date) => state.sessions.find((s) => s.date === date)?.totalReps || 0); const max = Math.max(20, ...values); const canvas = els.weeklyChart; ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, canvas.width, canvas.height); const padding = 34, plotWidth = canvas.width - padding * 2, plotHeight = canvas.height - padding * 2, gap = 6, barWidth = plotWidth / days.length - gap; ctx.strokeStyle = "#e1e5eb"; for (let i = 0; i <= 4; i++) { const y = padding + plotHeight / 4 * i; ctx.beginPath(); ctx.moveTo(padding, y); ctx.lineTo(canvas.width - padding, y); ctx.stroke(); } values.forEach((value, index) => { const height = value / max * plotHeight; const x = padding + index * plotWidth / days.length; ctx.fillStyle = value ? "#4285f4" : "#dfe6f1"; ctx.fillRect(x, padding + plotHeight - height, barWidth, Math.max(2, height)); }); ctx.fillStyle = "#5f6368"; ctx.font = "22px Arial"; ctx.textAlign = "center"; days.forEach((date, index) => { if (index % 3 === 0 || index === days.length - 1) ctx.fillText(date.slice(8), padding + index * plotWidth / days.length + barWidth / 2, canvas.height - 9); }); els.chartHint.textContent = values.filter(Boolean).length ? `${values.filter(Boolean).length} активных дней` : "Нет данных"; }
function calculateStreak() { const dates = new Set(state.sessions.map((s) => s.date)); let date = new Date(), streak = 0; while (dates.has(toDateKey(date))) { streak++; date.setDate(date.getDate() - 1); } return streak; }
function lastDays(count) { return Array.from({ length: count }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (count - index - 1)); return toDateKey(date); }); }
function clearData() { if (!state.sessions.length || !confirm("Удалить все записи тренировок?")) return; state.sessions = []; writeSessions(); renderAll(); }
async function shareBackup() { const fileName = `poyasnica-backup-${localDateKey()}.json`; const payload = JSON.stringify({ app: "Журнал упражнений для поясницы", version: 1, exportedAt: new Date().toISOString(), sessions: state.sessions }, null, 2); const file = new File([payload], fileName, { type: "application/json" }); try { if (navigator.share && navigator.canShare?.({ files: [file] })) { await navigator.share({ title: "Резервная копия тренировок", text: "Сохрани файл в Файлы → iCloud Drive.", files: [file] }); setBackupStatus(`Копия создана ${formatBackupTime()}`); return; } downloadBackup(file, fileName); setBackupStatus(`Файл скачан ${formatBackupTime()}`); } catch (error) { if (error.name !== "AbortError") { downloadBackup(file, fileName); setBackupStatus("Копия скачана в файлы"); } } }
function downloadBackup(file, fileName) { const url = URL.createObjectURL(file); const link = document.createElement("a"); link.href = url; link.download = fileName; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function restoreBackup(event) { const [file] = event.target.files; if (!file) return; try { const parsed = JSON.parse(await file.text()); const sessions = Array.isArray(parsed) ? parsed : parsed.sessions; if (!Array.isArray(sessions) || !sessions.every(isValidSession)) throw new Error(); if (state.sessions.length && !confirm("Заменить текущие записи данными из резервной копии?")) return; state.sessions = sessions.sort((a, b) => a.date.localeCompare(b.date)); writeSessions(); renderAll(); setBackupStatus(`Восстановлено записей: ${sessions.length}`); } catch { setBackupStatus("Не удалось прочитать файл"); } finally { event.target.value = ""; } }
function isValidSession(s) { return s && typeof s.date === "string" && Array.isArray(s.entries) && s.entries.every((e) => typeof e.id === "string" && Number.isFinite(e.reps)); }
function setBackupStatus(message) { els.backupStatus.textContent = message; } function formatBackupTime() { return new Intl.DateTimeFormat("ru-RU", { hour: "2-digit", minute: "2-digit" }).format(new Date()); }
function flashSaveButton() { const original = els.saveSessionButton.textContent; els.saveSessionButton.textContent = "Сохранено"; setTimeout(() => els.saveSessionButton.textContent = original, 1200); }
function readSessions() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; } catch { return []; } } function writeSessions() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.sessions)); }
function clampReps(value) { return Math.max(0, Math.min(200, Number.parseInt(value, 10) || 0)); } function formatDate(value) { return new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "long", year: "numeric" }).format(parseLocalDate(value)); }
function parseLocalDate(value) { const [year, month, day] = value.split("-").map(Number); return new Date(year, month - 1, day); } function toDateKey(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; } function localDateKey() { return toDateKey(new Date()); }
function escapeHtml(value) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char]); }
