const STORAGE_KEY = "lowerBackExerciseLog.v1";
const STORAGE_MODE_KEY = "lowerBackExerciseLog.storageMode.v1";

const exercises = [
  ["hyperextension", "Гиперэкстензия без отрыва ног", "15-20 повторений", "2020/08/Podem_koprusa_ruki_za_golovoj.gif", "Ляг на живот, ноги вместе, руки у затылка. Поднимай грудь и плечи без рывка, таз и ноги оставляй на полу.", "Укрепляет разгибатели спины, ягодицы и заднюю поверхность бедра."],
  ["down-up-dog", "Собака вниз в собаку вверх", "10-15 повторений", "2020/08/Iz_sobaki_mordoj_vniz_vverh.gif", "Из положения на руках уведи таз вверх, затем плавно опусти корпус и раскрой грудь в прогибе.", "Мягко вытягивает позвоночник, раскрывает грудной отдел и плечи."],
  ["bird-dog", "Вытягивание рук и ног", "10-15 на каждую сторону", "2020/10/Ohotnichya_sobaka_new.gif", "На четвереньках вытягивай противоположные руку и ногу в одну линию, затем спокойно меняй сторону.", "Развивает стабильность корпуса, координацию и мышцы поясницы."],
  ["glute-bridge", "Мостик, подъем таза лежа", "15-20 повторений", "2020/08/Mostik.gif", "Ляг на спину, стопы ближе к тазу. Поднимай таз до прямой линии от плеч до коленей и опускайся плавно.", "Укрепляет ягодицы и нижнюю часть спины, помогает стабилизировать таз."],
  ["boat", "Лодочка с руками вдоль тела", "10-15 повторений", "2020/08/Superman_ruki_nazad.gif", "Ляг на живот, руки вдоль корпуса. Одновременно чуть поднимай грудь и ноги, не запрокидывая голову.", "Включает мышцы спины, ягодицы и улучшает контроль корпуса."],
  ["plank-touch", "Касание рукой ноги из планки", "10-15 на каждую сторону", "2020/12/Planka_s_kasaniem_stop.gif", "Из планки на прямых руках уведи таз назад-вверх и тянись рукой к противоположной стопе.", "Нагружает кор, плечи, спину и заднюю поверхность ног."],
  ["cobra", "Низкая кобра в высокую", "10-15 повторений", "2020/08/Kobra_vverh_vniz-1.gif", "Лежа на животе, поставь ладони рядом с грудью и плавно поднимай корпус, сохраняя мягкий прогиб.", "Раскрывает грудную клетку, улучшает подвижность спины."],
  ["wipers", "Дворники с согнутыми ногами", "10-15 на каждую сторону", "2020/06/Dvornik_sognutie_koleni.gif", "Ляг на спину, руки в стороны, колени согнуты. Переводи ноги вправо и влево, контролируя поясницу.", "Мягко включает косые мышцы живота и снимает напряжение со спины."],
  ["reverse-plank", "Подъем таза из обратной планки", "10-15 повторений", "2020/07/Obratnaya_planka_podem_taza.gif", "Сядь, поставь руки позади таза, ноги вперед. Поднимай таз до прямой линии корпуса и опускай обратно.", "Укрепляет заднюю цепь, ягодицы, кор и поясничный отдел."],
  ["leg-raise", "Подъем ног лежа на животе", "10-15 на каждую сторону", "2020/07/Otvedenie_pryamoj_nogi.gif", "Ляг на живот, голову положи на предплечья. Поочередно поднимай прямые ноги без резкого маха.", "Укрепляет ягодицы, заднюю поверхность бедра и мышцы поясницы."],
].map(([id, name, target, image, technique, benefit]) => ({ id, name, target, image: `https://goodlooker.ru/wp-content/uploads/${image}`, technique, benefit }));

const moodLabels = { 5: "Отлично", 4: "Хорошо", 3: "Нормально", 2: "Тяжело", 1: "Плохо" };
const $ = (selector) => document.querySelector(selector);
const state = { sessions: readSessions(), selectedDate: localDateKey(new Date()), calendarMonth: new Date() };
const els = {
  screens: document.querySelectorAll(".screen"), navButtons: document.querySelectorAll(".bottom-nav button"), exerciseList: $("#exerciseList"), exerciseTemplate: $("#exerciseTemplate"), sessionDate: $("#sessionDate"), moodSelect: $("#moodSelect"), painRange: $("#painRange"), painValue: $("#painValue"), sessionNote: $("#sessionNote"), saveButton: $("#saveButton"), ringReps: $("#ringReps"), ringDone: $("#ringDone"), ringPain: $("#ringPain"), todayDateLabel: $("#todayDateLabel"), todayHeadline: $("#todayHeadline"), todayHint: $("#todayHint"), statSessions: $("#statSessions"), statReps: $("#statReps"), statStreak: $("#statStreak"), statPain: $("#statPain"), chart: $("#chart"), chartHint: $("#chartHint"), monthTitle: $("#monthTitle"), calendar: $("#calendar"), dayDetail: $("#dayDetail"), prevMonth: $("#prevMonth"), nextMonth: $("#nextMonth"), historyList: $("#historyList"), backupButton: $("#backupButton"), manualBackupButton: $("#manualBackupButton"), restoreButton: $("#restoreButton"), restoreInput: $("#restoreInput"), clearButton: $("#clearButton"), storageInputs: document.querySelectorAll('input[name="storageMode"]'), storageNote: $("#storageNote"), backupStatus: $("#backupStatus")
};
init();
function init(){els.sessionDate.value=localDateKey(new Date());state.selectedDate=els.sessionDate.value;renderExercises();bindEvents();setStorageMode(localStorage.getItem(STORAGE_MODE_KEY)||"device");renderAll();}
function bindEvents(){els.navButtons.forEach((b)=>b.addEventListener("click",()=>switchScreen(b.dataset.screen)));els.painRange.addEventListener("input",()=>{els.painValue.textContent=`${els.painRange.value}/10`;updateTodayPreview();});els.sessionDate.addEventListener("change",()=>{state.selectedDate=els.sessionDate.value||localDateKey(new Date());updateTodayPreview();});els.saveButton.addEventListener("click",saveSession);els.prevMonth.addEventListener("click",()=>shiftMonth(-1));els.nextMonth.addEventListener("click",()=>shiftMonth(1));els.backupButton.addEventListener("click",shareBackup);els.manualBackupButton.addEventListener("click",shareBackup);els.restoreButton.addEventListener("click",()=>els.restoreInput.click());els.restoreInput.addEventListener("change",restoreBackup);els.clearButton.addEventListener("click",clearData);els.storageInputs.forEach((i)=>i.addEventListener("change",()=>setStorageMode(i.value)));}
function renderExercises(){els.exerciseList.innerHTML="";exercises.forEach((exercise,index)=>{const node=els.exerciseTemplate.content.firstElementChild.cloneNode(true);node.dataset.exerciseId=exercise.id;node.querySelector(".exercise-index").textContent=index+1;node.querySelector("strong").textContent=exercise.name;node.querySelector("small").textContent=exercise.target;node.querySelector("img").src=exercise.image;node.querySelector("img").alt=exercise.name;node.querySelector(".technique").textContent=exercise.technique;node.querySelector(".benefit").textContent=exercise.benefit;const input=node.querySelector("input");input.value=0;input.dataset.exerciseId=exercise.id;input.setAttribute("aria-label",`${exercise.name}, повторы`);input.addEventListener("input",updateTodayPreview);node.querySelector(".minus").addEventListener("click",()=>step(input,-1));node.querySelector(".plus").addEventListener("click",()=>step(input,1));node.querySelector(".exercise-info").addEventListener("click",()=>node.classList.toggle("open"));els.exerciseList.append(node);});}
function step(input,delta){input.value=Math.max(0,Math.min(200,Number(input.value||0)+delta));updateTodayPreview();}
function getEntries(){return exercises.map((exercise)=>({id:exercise.id,name:exercise.name,reps:clampReps($(`input[data-exercise-id="${exercise.id}"]`).value)}));}
function saveSession(){const entries=getEntries();const totalReps=entries.reduce((sum,entry)=>sum+entry.reps,0);const session={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:els.sessionDate.value||localDateKey(new Date()),mood:Number(els.moodSelect.value),pain:Number(els.painRange.value),note:els.sessionNote.value.trim(),entries,totalReps,savedAt:new Date().toISOString()};const existingIndex=state.sessions.findIndex((item)=>item.date===session.date);if(existingIndex>=0)state.sessions[existingIndex]=session;else state.sessions.push(session);state.sessions.sort((a,b)=>a.date.localeCompare(b.date));state.selectedDate=session.date;state.calendarMonth=parseLocalDate(session.date);writeSessions();renderAll();flashSaved();if(getStorageMode()==="icloud")shareBackup();}
function renderAll(){updateTodayPreview();renderStats();drawChart();renderCalendar();renderDayDetail();renderHistory();}
function updateTodayPreview(){const entries=getEntries();const total=entries.reduce((sum,entry)=>sum+entry.reps,0);const done=entries.filter((entry)=>entry.reps>0).length;const pain=Number(els.painRange.value);const saved=state.sessions.find((session)=>session.date===(els.sessionDate.value||state.selectedDate));els.ringReps.textContent=total;els.ringDone.textContent=`${done}/10`;els.ringPain.textContent=pain;$(".ring-reps").style.setProperty("--value",Math.min(100,total/1.5).toFixed(0));$(".ring-done").style.setProperty("--value",(done*10).toFixed(0));$(".ring-pain").style.setProperty("--value",(pain*10).toFixed(0));els.todayDateLabel.textContent=formatDate(els.sessionDate.value||state.selectedDate);els.todayHeadline.textContent=saved?`${saved.totalReps} повторений сохранено`:total?`${total} повторений набрано`:"Тренировка не сохранена";els.todayHint.textContent=done?`${done} из 10 упражнений с повторами`:"Выстави повторы и сохрани занятие.";}
function renderStats(){const total=state.sessions.reduce((sum,session)=>sum+session.totalReps,0);const avgPain=state.sessions.length?state.sessions.reduce((sum,session)=>sum+session.pain,0)/state.sessions.length:0;els.statSessions.textContent=state.sessions.length;els.statReps.textContent=total;els.statStreak.textContent=calculateStreak();els.statPain.textContent=avgPain.toFixed(1);}
function drawChart(){const ctx=els.chart.getContext("2d");const days=lastDays(14);const values=days.map((date)=>state.sessions.find((session)=>session.date===date)?.totalReps||0);const max=Math.max(20,...values);const width=els.chart.width;const height=els.chart.height;ctx.clearRect(0,0,width,height);const padding=34;const plotHeight=height-padding*2;const barWidth=(width-padding*2)/days.length-8;values.forEach((value,index)=>{const x=padding+index*((width-padding*2)/days.length);const barHeight=Math.max(3,(value/max)*plotHeight);const y=padding+plotHeight-barHeight;const gradient=ctx.createLinearGradient(0,y,0,y+barHeight);gradient.addColorStop(0,value?"#ff2d55":"rgba(255,255,255,.18)");gradient.addColorStop(1,value?"#ff9f0a":"rgba(255,255,255,.08)");roundRect(ctx,x,y,barWidth,barHeight,10,gradient);});ctx.fillStyle="rgba(255,255,255,.46)";ctx.font="22px -apple-system, sans-serif";ctx.textAlign="center";days.forEach((date,index)=>{if(index%3===0||index===days.length-1)ctx.fillText(date.slice(8),padding+index*((width-padding*2)/days.length)+barWidth/2,height-10);});els.chartHint.textContent=values.filter(Boolean).length?`${values.filter(Boolean).length} активных дней`:"Нет данных";}
function renderCalendar(){els.calendar.innerHTML="";const year=state.calendarMonth.getFullYear();const month=state.calendarMonth.getMonth();const sessions=state.sessions.filter((session)=>{const date=parseLocalDate(session.date);return date.getFullYear()===year&&date.getMonth()===month;});const max=Math.max(1,...sessions.map((session)=>session.totalReps));els.monthTitle.textContent=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(state.calendarMonth);const first=new Date(year,month,1);const blanks=(first.getDay()+6)%7;const days=new Date(year,month+1,0).getDate();for(let index=0;index<blanks;index+=1)els.calendar.append(createBlankDay());for(let day=1;day<=days;day+=1){const key=localDateKey(new Date(year,month,day));const session=state.sessions.find((item)=>item.date===key);const button=document.createElement("button");button.className="day";button.type="button";button.textContent=day;if(session){button.classList.add("has-session");button.style.setProperty("--load",Math.max(.22,session.totalReps/max).toFixed(2));}if(key===state.selectedDate)button.classList.add("selected");button.addEventListener("click",()=>{state.selectedDate=key;renderCalendar();renderDayDetail();});els.calendar.append(button);}}
function renderDayDetail(){const session=state.sessions.find((item)=>item.date===state.selectedDate);if(!session){els.dayDetail.innerHTML=`<article class="day-card"><p>${formatDate(state.selectedDate)}: тренировки нет.</p></article>`;return;}const done=session.entries.filter((entry)=>entry.reps>0).length;const top=[...session.entries].sort((a,b)=>b.reps-a.reps)[0];els.dayDetail.innerHTML=`<article class="day-card"><strong>${formatDate(session.date)} · ${session.totalReps} повторений</strong><p>${done}/10 упражнений · ${moodLabels[session.mood]} · боль ${session.pain}/10</p><p>Максимум: ${top.name}, ${top.reps}</p></article>`;}
function renderHistory(){const sessions=[...state.sessions].sort((a,b)=>b.date.localeCompare(a.date));els.historyList.innerHTML=sessions.length?"":`<article class="history-entry"><p>Записей пока нет.</p></article>`;sessions.forEach((session)=>{const done=session.entries.filter((entry)=>entry.reps>0).length;const article=document.createElement("article");article.className="history-entry";article.innerHTML=`<header><span>${formatDate(session.date)}</span><span>${session.totalReps}</span></header><p>${done}/10 упражнений · ${moodLabels[session.mood]} · боль ${session.pain}/10</p>${session.note?`<p>${escapeHtml(session.note)}</p>`:""}`;els.historyList.append(article);});}
function switchScreen(screen){els.screens.forEach((item)=>item.classList.toggle("active",item.id===`${screen}Screen`));els.navButtons.forEach((button)=>button.classList.toggle("active",button.dataset.screen===screen));if(screen==="stats")drawChart();}
function shiftMonth(direction){state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()+direction,1);renderCalendar();}
function getStorageMode(){return document.querySelector('input[name="storageMode"]:checked')?.value||"device";}
function setStorageMode(mode){const normalized=mode==="icloud"?"icloud":"device";els.storageInputs.forEach((input)=>{input.checked=input.value===normalized;});localStorage.setItem(STORAGE_MODE_KEY,normalized);if(normalized==="icloud"){els.storageNote.textContent="После сохранения iPhone предложит сохранить JSON-файл в iCloud Drive.";els.backupStatus.textContent="iCloud Drive";}else{els.storageNote.textContent="Статистика хранится в браузере на этом iPhone.";els.backupStatus.textContent="На iPhone";}}
async function shareBackup(){const fileName=`poyasnica-backup-${localDateKey(new Date())}.json`;const file=new File([JSON.stringify({app:"Поясница v2",version:2,sessions:state.sessions},null,2)],fileName,{type:"application/json"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"Резервная копия тренировок",text:"Сохрани файл в iCloud Drive.",files:[file]});}else{const url=URL.createObjectURL(file);const link=document.createElement("a");link.href=url;link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}
async function restoreBackup(event){const [file]=event.target.files;if(!file)return;const parsed=JSON.parse(await file.text());const sessions=Array.isArray(parsed)?parsed:parsed.sessions;if(!Array.isArray(sessions))return;state.sessions=sessions;writeSessions();renderAll();event.target.value="";}
function clearData(){if(!state.sessions.length||!confirm("Удалить все записи?"))return;state.sessions=[];writeSessions();renderAll();}
function flashSaved(){const text=els.saveButton.textContent;els.saveButton.textContent="Сохранено";setTimeout(()=>{els.saveButton.textContent=text;},1200);}
function createBlankDay(){const blank=document.createElement("span");blank.className="day blank";return blank;}
function calculateStreak(){const dates=new Set(state.sessions.map((session)=>session.date));let date=new Date();let count=0;while(dates.has(localDateKey(date))){count+=1;date.setDate(date.getDate()-1);}return count;}
function lastDays(count){return Array.from({length:count},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(count-index-1));return localDateKey(date);});}
function readSessions(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[];}catch{return[];}}
function writeSessions(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.sessions));}
function clampReps(value){return Math.max(0,Math.min(200,Number.parseInt(value,10)||0));}
function localDateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function parseLocalDate(value){const [year,month,day]=value.split("-").map(Number);return new Date(year,month-1,day);}
function formatDate(value){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"long",year:"numeric"}).format(parseLocalDate(value));}
function escapeHtml(value){return value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);}
function roundRect(ctx,x,y,width,height,radius,fillStyle){ctx.fillStyle=fillStyle;ctx.beginPath();ctx.moveTo(x+radius,y);ctx.arcTo(x+width,y,x+width,y+height,radius);ctx.arcTo(x+width,y+height,x,y+height,radius);ctx.arcTo(x,y+height,x,y,radius);ctx.arcTo(x,y,x+width,y,radius);ctx.closePath();ctx.fill();}
